// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04FjotE0vQpXCG767CO3RG0zdMSRoLOw',
    appId: '1:728140410192:web:08a68e676d625a878f9055',
    messagingSenderId: '728140410192',
    projectId: 'applyyc-3860f',
    authDomain: 'applyyc-3860f.firebaseapp.com',
    storageBucket: 'applyyc-3860f.appspot.com',
    measurementId: 'G-CM7MJ6YFWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJl_MWCQUmusb5Zr_qBgTqS7M0uB5xCYI',
    appId: '1:728140410192:android:9fc21f5c88ffa59a8f9055',
    messagingSenderId: '728140410192',
    projectId: 'applyyc-3860f',
    storageBucket: 'applyyc-3860f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LdDh49I-N3DVkgwr737iuiSiKUuvWEE',
    appId: '1:728140410192:ios:d27987e568b7f6398f9055',
    messagingSenderId: '728140410192',
    projectId: 'applyyc-3860f',
    storageBucket: 'applyyc-3860f.appspot.com',
    iosClientId: '728140410192-er3g911val4jcg2v0s1s5dulhmg4i4so.apps.googleusercontent.com',
    iosBundleId: 'com.example.applyYc',
  );
}
